name: Docker CI/CD

on:
  push:
    branches:
      - main  # Adjust to match your main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted  # This runs on your self-hosted runner

    env:
      REGISTRY: "amorimmg/portfolio"
      DOCKER_TAG: "1.${{ github.run_number }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Stop Previous Container
        run: |
          CONTAINERS=$(docker ps -a --format "{{.ID}} {{.Image}}" | grep $REGISTRY | awk '{print $1}')
          for CONTAINER in $CONTAINERS; do
            docker stop $CONTAINER || true
          done

      - name: Build Docker Image
        run: |
          docker build -t $REGISTRY:$DOCKER_TAG .

      - name: Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push $REGISTRY:$DOCKER_TAG

      - name: Deploy New Container
        run: |
          docker run --restart=always --name portfolio-$DOCKER_TAG --network bridge -d -p 5173:5173 $REGISTRY:$DOCKER_TAG

      - name: Clean Up Exited Containers
        run: |
          EXITED_CONTAINERS=$(docker ps -a --filter "status=exited" --format "{{.ID}} {{.Image}}" | grep $REGISTRY | awk '{print $1}')
          for CONTAINER in $EXITED_CONTAINERS; do
            docker rm -v $CONTAINER || true
          done
